### ISSUE TITLE
MSBuild target fails in Docker build / GitHub actions: System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by SapiensAnatis** [dotnet/Nerdbank.GitVersioning#1080]
Hey! Thanks for this tool, it has stopped me from repeatedly re-writing the `latest` tag on all my images, it's great to be able to have proper tags in case I need to revert.

I just wanted to flag an issue I ran into with the MSBuild integration when running in a Docker container in Github Actions. I was getting the following error while building my image:

```
#24 4.482 /root/.nuget/packages/nerdbank.gitversioning/3.6.141/build/Nerdbank.GitVersioning.targets(94,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly. [/src/Shared/DragaliaAPI.Photon.Shared/DragaliaAPI.Photon.Shared.csproj]
#24 4.484 /root/.nuget/packages/nerdbank.gitversioning/3.6.141/build/Nerdbank.GitVersioning.targets(94,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/runner/work/_temp/_runner_file_commands/set_env_0a79b4bc-b34e-4fa9-bf2c-debe8836dfd6'. [/src/Shared/DragaliaAPI.Photon.Shared/DragaliaAPI.Photon.Shared.csproj]
```

I was getting this after setting the GitHub variables as described in the [Docker cloud build documentation](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/cloudbuild.md#docker-build). So my step looked like this:

```yaml
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: DragaliaAPI/DragaliaAPI/Dockerfile
          tags: ghcr.io/sapiensanatis/dragalia-api${{ steps.nbgv.outputs.SemVer2 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }} 
            org.opencontainers.image.revision=${{ github.sha }} 
            org.opencontainers.image.authors=github.com/${{ github.repository_owner }}
          build-args: |
            GITHUB_ACTIONS=true
            GITHUB_EVENT_NAME=${{ github.event_name }}
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
            GITHUB_ENV=${{ github.env }}
```

and during the build my Dockerfile would take these args:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0.401 AS build

ARG GITHUB_ACTIONS
ARG GITHUB_EVENT_NAME
ARG GITHUB_SHA
ARG GITHUB_REF
ARG GITHUB_ENV

# ... package restore, etc ...

RUN dotnet publish "DragaliaAPI.csproj" -c Release -o /app/publish/ /p:UseAppHost=false
```

Here the build context is `.` without any change of directory, so it is the root of the repo, and it encompasses:

```
.
├── DragaliaAPI
│   ├── version.json
│   └── DragaliaAPI
│       └── Dockerfile
└── .git
```

so Nerdbank should have everything it needs.

---

I added a `realpath .` debug step and found that the path of `.` actually equates to `/home/runner/work/Dawnshard/Dawnshard`, but the action via `GITHUB_ENV` is attempting to access `/home/runner/work/_temp/_runner_file_commands/set_env_0a79b4bc-b34e-4fa9-bf2c-debe8836dfd6` which is not part of the Docker build context as it isn't inside of the repository directory. I would assume this is why it is failing.

Interestingly, setting `$.cloudBuild.setVersionVariables` to `false` doesn't seem to disable this target, but one workaround is to just... not pass any `GITHUB_XXX` variables into the Docker build, in which case I'm assuming Nerdbank doesn't trigger any cloud build logic.

It is not terribly important for me to have the assembly versions set as long as I have the correct Docker tag, so I am satisfied with this workaround for now. But I thought I would mention this issue in case there is something to fix or in case the docs need updating.
