### ISSUE TITLE
Customization of build number stamping on assembly

### ISSUE THREAD

**Issue by AnkieSahu** [dotnet/Nerdbank.GitVersioning#488]
I am trying to customize build number stamping, by default its supports x.x.x (major minor and patch) but for hotfix i want to stamp x.x.x.{hotfix-version} on assembly, but it didn't worked for me.

I am using below script in build definition Yaml:-

```yaml
- script: |
    dotnet tool install --tool-path . nbgv
    .\nbgv cloud -c
  displayName: Set build number
```

And in version.json:

```json
{
"$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",

"version": "2.0",
"publicReleaseRefSpec": [
"^refs/heads/master$"
],
"cloudBuild": {
"setVersionVariables": true
}
}
```
