### ISSUE TITLE
Use isOutput=true when writing variables in Azure DevOps

### ISSUE THREAD

**Issue by goldsam** [dotnet/Nerdbank.GitVersioning#859]
Using variables written in one job/stage in Azure Devops from a later job/stage currently requires re-exporting NBGV_* variables resulting in needlessly complex azure pipeline files. Would it be possible to add a cli flag to that variables written in a devops environment will include `isoutput=true`?

https://github.com/dotnet/Nerdbank.GitVersioning/blob/981ef2afdfedc87128d736875f7f79b4a835e621/src/NerdBank.GitVersioning/CloudBuildServices/VisualStudioTeamServices.cs#L39-L44

**Comment by AArnott** [comment]
That's a great idea. I don't think we need a _flag_ for this, since converting a variable to an output variables only expands scope AFAIK. Would you care to send the PR?

**Comment by goldsam** [comment]
Unfortunately, _output_ variable references must include the `name` of the step in which they were written. This is different from _standard_ variable references which don't required any qualifier. The following pipeline snippet demonstrates this:

```yaml
steps:
- bash: |
    echo '##vso[task.setvariable variable=myCondStandardVar]true'
    echo '##vso[task.setvariable variable=myCondOutputVar;isOutput=true]true'
  displayName: "settting variables"
  name: myStep
- bash: |
    echo myCondStandardVar: $(myCondStandardVar)
    echo myCondOutputVar: $(myStep.myCondOutputVar)
```

I believe simply adding `isOutput=true` would introduce a breaking change. Aside from introducing a flag, the only solution I can think of would be to write each variable twice as a _standard_ and _output_ variable (using distinct names). That idea seems unclean to me. What are your thoughts?

**Comment by AArnott** [comment]
I think writing it out twice is a fine idea. We certainly don't want to break backward compat, and offering an option that gives the output variable but at the expense of breaking whatever the user has that depends on regular variables is sad too. I just wonder why AzP doesn't allow for writing out a variable that does both jobs with one log command, but I don't mind if we do it twice.

**Comment by ronaldbarendse** [comment]
What about checking an environment variable to switch to output variables instead, e.g. `NBGV_CloudBuild_IsOutput`? And maybe add the possibility to specify specific variables to set as output, so besides true/false, also allow setting `NBGV_GitBuildVersion;NBGV_GitBuildVersionSimple` to prevent outputting all variables?

```yaml
jobs:
- job: A
  variables:
    NBGV_CloudBuild_IsOutput: true
  steps:
  - script: dotnet tool install --tool-path . nbgv
  - script: ./nbgv get-version
    name: getversion
- job: B
  dependsOn: A
  variables:
    buildVersion: $[ dependencies.A.outputs['getversion.NBGV_GitBuildVersion'] ]  
  steps:
  - script: echo $(buildVersion)
```

Implementing it this way will only require changes to the build pipeline to opt-in to writing output variables and changing the syntax to use the task name...
