### ISSUE TITLE
How to rebuild past tagged builds as public releases? / Add BuildingRef override

### ISSUE THREAD

**Issue by georg-jung** [dotnet/Nerdbank.GitVersioning#873]
My use case: I have a GitHub Actions cron job that checks if my docker base images have updated. If they have, it checks out the latest release tag according to GitHub Releases and rebuilds my Docker images.

My `version.json` looks like this:

```json
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.7",
  "publicReleaseRefSpec": [
    "^refs/heads/release/v\\d+(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

As I'm checking out a different commit than the one chosen by GitHub (which defaults to the newest commit on the default branch for a cron job), the information in `GITHUB_REF` is stale. Now, I've seen #795 and adapted my workflow config accordingly:

(Assume a tag e.g. `v0.7.3` as `inputs.build-ref`)

```yml
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        ref: ${{ inputs.build-ref }}
    - uses: dotnet/nbgv@v0.4
      id: nbgv
      with:
        # see https://github.com/dotnet/nbgv/issues/50
        # remove this as soon as nbgv 3.6.x+ is released
        toolVersion: 3.6.65-alpha # or later
        toolFeed: https://pkgs.dev.azure.com/andrewarnott/OSS/_packaging/PublicCI/nuget/v3/index.json
      env:
        # if we checkout a build ref from input above, this is important
        IGNORE_GITHUB_REF: true # see https://github.com/dotnet/Nerdbank.GitVersioning/blob/274a42ed3321bcc43632dc970d65677f99a486a9/src/NerdBank.GitVersioning/CloudBuildServices/GitHubActions.cs#L32
```

As expected, the resulting `BuildingRef` does not point to the stale information from `GITHUB_REF` anymore, which is great.

However, nbgv also tells that I'm not building a public release now. I am, however, at a commit that is part of a `release/v0.7` branch and also at the commit where `v0.7.3` points. This is easy to reproduce locally:

`git checkout refs/tags/v0.7.3` results in a detached head state. Executing `nbgv get-version -f json` afterwards also shows a non-public release. Now I think it might make sense for detached heads to assume they are non-public. Also, looking at what I believe is the [relevant code](https://github.com/dotnet/Nerdbank.GitVersioning/blob/274a42ed3321bcc43632dc970d65677f99a486a9/src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs#L278), this makes sense.

To summarize, my intention is to build from a tagged past commit again in exactly the same way as when the tag was created. GitHub Actions does not allow changing the `GITHUB_REF`, so changing the environment accordingly is not possible.

Options that came to my mind:
* add a `BuildingRef` override by env variable
  * probably change [this line](https://github.com/dotnet/Nerdbank.GitVersioning/blob/274a42ed3321bcc43632dc970d65677f99a486a9/src/NerdBank.GitVersioning/VersionOracle.cs#L63) to something similar to `this.BuildingRef = buildingRefOverrideFromEnv ?? cloudBuild?.BuildingTag ?? cloudBuild?.BuildingBranch ?? context.HeadCanonicalName;`
  * This also adds a lot more flexibility for a lot of other use cases than this specific one.
* add an equivalent of `git tag --points-at HEAD` to [`GitRepository.GetHeadAsReferenceOrSha()`](https://github.com/dotnet/Nerdbank.GitVersioning/blob/274a42ed3321bcc43632dc970d65677f99a486a9/src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs#L278)

Is there any smarter way around this? What do you think?

Complete example workflow runs:
* [Original run triggered by publishing a new github release, works](https://github.com/akademischerverein/ava/actions/runs/3249084677/jobs/5331068018)
* [Re-run on same commit, checked out by tag, does not work (non-public release)](https://github.com/akademischerverein/ava/actions/runs/3695998306/jobs/6259113295)

**Comment by AArnott** [comment]
Thanks for this excellent write-up. To get you unblocked, I want to first offer you the available workaround: Set `PublicRelease=true` as an environment variable (or msbuild property). 

Now as to your suggestions...

I take it GitHub doesn't set any environment variable with the name of the tag or branch that was checked out when you override the default commit to checkout. Is that correct? If no env var exists, allowing the user to set one manually makes sense IMO.

I like the `git tag --points-at` idea as a means to *automatically* consider something a public release if any tag that points at a commit conforms to the publicReleaseRefSpec. Doing the right thing automatically sounds great. Possibly in addition to your env var override idea.

**Comment by georg-jung** [comment]
> I take it GitHub doesn't set any environment variable with the name of the tag or branch that was checked out when you override the default commit to checkout. Is that correct?

If I understand it correctly, every workflow run has a commit it belongs to. See [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows), the `GITHUB_REF` cells in all those small tables per trigger. A workflow does not necessarily check anything out from git though and what it checks out can be overriden by using `ref` with checkout

```yml
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        ref: ${{ inputs.build-ref }}
```

What is checked out is then in no way related to the commit the current workflow run is assigned to. Still every workflow is always assigned to a commit and that assignment is available in `GITHUB_REF`.

My idea was to provide a `BuildingRef` override, in the same way the checkout itself can be overriden. Usage could work like this:

```yml
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        ref: ${{ inputs.build-ref }}
    - uses: dotnet/nbgv@v0.4
      id: nbgv
      with:
        buildingRef: ${{ inputs.build-ref }}
```
